import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import AppProvider from "@/components/app-provider";
import ReactQueryInstance from "@/components/react-query";
import { getMessages, setRequestLocale } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

// fonts chữ
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// SEO page
export const metadata: Metadata = {
  title: "QRTable",
  description: "Generated by create next app",
};

// generateStaticParams đây là 1 api của next giúp render ra các ngôn ngữ, ví dụ trang có 2 ngôn ngữ là vi và en thì nó sẽ kết hợp với setRequestLocale để hiện thị đúng trang html tĩnh (đúng ngôn ngữ hiện tại)
// nhờ generateStaticParams render ra nhiều html tĩnh khiến page từ dynamic -> static, còn nếu ko có generateStaticParams thì page sẽ là dynamic, mỗi lần có request vào thì mới render ra html tương ứng với ngôn ngữ đó
// Ví dụ: Nếu có ["en", "vi"], Next.js sẽ build ra /en/... và /vi/... dưới dạng static HTML.
// ○ Static: file tĩnh, không có params, không cần generateStaticParams.
// ● SSG: static HTML, nhưng có params, dùng generateStaticParams để build ra nhiều file tĩnh cho từng trường hợp.

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const locale = (await params).locale;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale); // Thiết lập locale cho request hiện tại - Đặt ngôn ngữ cho toàn bộ Server Components trong request đó - chỉ dùng dc cho server component 

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <ReactQueryInstance>
            <AppProvider>
              <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                {children}
                <Toaster position="top-center" />
              </ThemeProvider>
            </AppProvider>
          </ReactQueryInstance>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
